name: Android CI
env:
  CI_KEYSTORE: ${{ secrets.CODESTER_KEY }}
  CI_KEYSTORE_ALIAS: ${{ secrets.CODESTER_ALIAS }}
  CI_KEYSTORE_KEY_PASSWORD: ${{ secrets.CODESTER_KEY_PASSWORD }}
  CI_KEYSTORE_STORE_PASSWORD: ${{ secrets.CODESTER_STORE_PASSWORD }}
  
on:
  push: 
   branches:
    -'*'
    -'!playstore*'
  pull_request:
   branches:
    -'*'
    -'!playstore*'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    
    - name: Cache
      uses: actions/cache@v2.1.4
      with:
        path: |
         ~/.gradle/caches/modules-*
         ~/.gradle/caches/jars-*
         ~/.gradle/caches/build-cache-*
         ~/.gradle/*
         ./*/build/*
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties','./*/build/*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
     
    - name: Create CI key
      run : echo $CI_KEYSTORE | base64 -i -d > app/ci_key.jks
        
    - name: Build with Gradle
      run: ./gradlew assembleRelease bundleRelease
      
