name: Codester CI
env:
  CI_KEYSTORE: ${{ secrets.CODESTER_KEY }}
  CI_KEYSTORE_ALIAS: ${{ secrets.CODESTER_ALIAS }}
  CI_KEYSTORE_KEY_PASSWORD: ${{ secrets.CODESTER_KEY_PASSWORD }}
  CI_KEYSTORE_STORE_PASSWORD: ${{ secrets.CODESTER_STORE_PASSWORD }}
  BUILD_TOOLS_VERSION: "30.0.3"
on: 
    push:
      branches:
        - 'codester'
    pull_request:
      branches:
        - 'codester'

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Cache
        uses: actions/cache@v2.1.4
        with:
         path: |
           ~/.gradle/caches/modules-*
           ~/.gradle/caches/jars-*
           ~/.gradle/caches/build-cache-*
           ~/.gradle/*
           ./*/build/*
         key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties','./*/build/*') }}
         restore-keys: |
          ${{ runner.os }}-gradle-
      
      - name: Create Tag
        run: | 
          export TAG=$(git rev-parse --short HEAD)
          echo $TAG
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "RELEASE_NAME=Codester-$TAG" >> $GITHUB_ENV
          
      - name: Grant rights
        run: chmod +x gradlew

      - name: Create CI key
        run : echo $CI_KEYSTORE | base64 -i -d > app/ci_key.jks
      - name: Build Release APK & AAB
        id: buildRelease
        run: ./gradlew assembleRelease bundleRelease
        
      - name: Create Github Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            app/build/outputs/apk/full/release/app-full-release.apk
            app/build/outputs/apk/mobile/release/app-mobile-release.apk
            app/build/outputs/apk/tv/release/app-tv-release.apk
            app/build/outputs/bundle/fullRelease/app-full-release.aab
            app/build/outputs/bundle/mobileRelease/app-mobile-release.aab
            app/build/outputs/bundle/tvRelease/app-tv-release.aab
#          tag: ${{ env.TAG }}
          automatic_release_tag: ${{ env.TAG }}
          title: ${{ env.RELEASE_NAME }}
