name: Release CI
env:
  CI_KEYSTORE: ${{ secrets.PLAYSTORE_KEY }}
  CI_KEYSTORE_ALIAS: ${{ secrets.PLAYSTORE_ALIAS }}
  CI_KEYSTORE_KEY_PASSWORD: ${{ secrets.PLAYSTORE_KEY_PASSWORD }}
  CI_KEYSTORE_STORE_PASSWORD: ${{ secrets.PLAYSTORE_STORE_PASSWORD }}
  BUILD_TOOLS_VERSION: "30.0.3"
on:
  release:
    types: [created]
#    tags: 
#      - '*'
    branches:
      - 'playstore'

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Cache
        uses: actions/cache@v2.1.4
        with:
         path: |
           ~/.gradle/caches/modules-*
           ~/.gradle/caches/jars-*
           ~/.gradle/caches/build-cache-*
         key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
         restore-keys: |
          ${{ runner.os }}-gradle-
    
      - name: Grant rights
        run: chmod +x gradlew
        

      - name: Build Release APK & AAB
        id: buildRelease
        run: ./gradlew assembleRelease bundleRelease
      - name: Upload Release Assets
        uses: meeDamian/github-release@2.0
        with:
          allow_override: true
          token: ${{ secrets.GITHUB_TOKEN }}
          gzip: false
          files: >
            app/build/outputs/apk/full/release/app-full-release.apk
            app/build/outputs/apk/mobile/release/app-mobile-release.apk
            app/build/outputs/apk/tv/release/app-tv-release.apk
            app/build/outputs/bundle/fullRelease/app-full-release.aab
            app/build/outputs/bundle/mobileRelease/app-mobile-release.aab
            app/build/outputs/bundle/tvRelease/app-tv-release.aab
